// File generated by FlutterFire CLI (manually completed — cf. Q-20 / issue #174).
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web — '
        'run flutterfire configure to reconfigure.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKBeQ7bGFyiWGic8ZW76A6MlG3ulqXIKA',
    appId: '1:61286833902:android:bc1df280dfec8d4d8e1dff',
    messagingSenderId: '61286833902',
    projectId: 'murabbi-90798',
    storageBucket: 'murabbi-90798.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA01sFf8EKuW4RWgywxzmcTPXUjKIRSx6o',
    appId: '1:61286833902:ios:4c4b42f5d5602b788e1dff',
    messagingSenderId: '61286833902',
    projectId: 'murabbi-90798',
    storageBucket: 'murabbi-90798.firebasestorage.app',
    iosBundleId: 'com.murabbi.murabbi',
  );
}
